import os
from datetime import datetime

# ==============================================================================
# 路径解析 (完全对齐你的动态路径标准)
# ==============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
ROOT_DIR = os.path.dirname(PROJECT_DIR)
DATA_DIR = os.path.join(PROJECT_DIR, "data")

def main():
    domains = set()

    # 1. 读取基础底座
    base_file_path = os.path.join(DATA_DIR, "us_stock_backbone_base.txt")
    if os.path.exists(base_file_path):
        with open(base_file_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"): continue
                if line.startswith("- "): line = line[2:].strip()
                domains.add(line)

    # 2. 读取雷达动态数据
    discovered_file_path = os.path.join(DATA_DIR, "us_stock_backbone_discovered.txt")
    if os.path.exists(discovered_file_path):
        with open(discovered_file_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"): continue
                if line.startswith("- "): line = line[2:].strip()
                domains.add(line)

    if not domains: return

    sorted_domains = sorted(list(domains))
    total_count = len(sorted_domains)
    update_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 3. 生成 .yaml (Clash)
    with open(os.path.join(ROOT_DIR, "us_stock_backbone.yaml"), "w", encoding="utf-8") as f:
        f.write(f"# Title: US Stock Backbone (Clash Payload)\n# Count: {total_count}\n# Updated: {update_time}\npayload:\n")
        for d in sorted_domains: f.write(f"  - '{d}'\n")

    # 4. 生成 .list (通用)
    with open(os.path.join(ROOT_DIR, "us_stock_backbone.list"), "w", encoding="utf-8") as f:
        for d in sorted_domains: f.write(f"{d}\n")

    # 5. 生成 .srs (兼容 Surge/Quantumult)
    with open(os.path.join(ROOT_DIR, "us_stock_backbone.srs"), "w", encoding="utf-8") as f:
        for d in sorted_domains: f.write(f"{d}\n")

    # 6. 更新 README 看板
    with open(os.path.join(PROJECT_DIR, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# US Stock Backbone Rules\n\n![Updated](https://img.shields.io/badge/Updated-{update_time.split()[0]}-green)\n\n### Statistics\n\n| Category | Type | Count |\n| :--- | :--- | :--- |\n| Base | Manual | {total_count} |\n| Total | Combined | **{total_count}** |\n\n### Files\n\n- [us_stock_backbone.yaml](us_stock_backbone.yaml)\n- [us_stock_backbone.list](us_stock_backbone.list)\n- [us_stock_backbone.srs](us_stock_backbone.srs)\n\n### Auto Update\n\nThis file is automatically generated by GitHub Actions.")

    print(f"[+] 编译完成: 生成了 .yaml, .list, .srs 三种格式，共 {total_count} 条规则。")

if __name__ == "__main__":
    main()
