import os
from datetime import datetime

# 路径设置
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
ROOT_DIR = os.path.dirname(PROJECT_DIR)
DATA_DIR = os.path.join(PROJECT_DIR, "data")

def main():
    domains = set()
    
    # 定义两个数据源
    sources = [
        os.path.join(DATA_DIR, "us_stock_backbone_base.txt"),
        os.path.join(DATA_DIR, "us_stock_backbone_discovered.txt")
    ]
    
    # 1. 读取并标准化所有域名
    for source in sources:
        if os.path.exists(source):
            with open(source, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"): continue
                    # 剥离所有前缀，只留纯域名
                    clean = line.replace("DOMAIN-SUFFIX,", "").replace("+.", "").replace("DOMAIN,", "")
                    domains.add(clean)

    sorted_domains = sorted(list(domains))
    total_count = len(sorted_domains)
    update_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 2. 生成 .yaml (格式: payload: \n  - +.domain)
    with open(os.path.join(ROOT_DIR, "us_stock_backbone.yaml"), "w", encoding="utf-8") as f:
        f.write("payload:\n")
        for d in sorted_domains:
            f.write(f"  - +.{d}\n")

    # 3. 生成 .list (格式: +.domain)
    with open(os.path.join(ROOT_DIR, "us_stock_backbone.list"), "w", encoding="utf-8") as f:
        for d in sorted_domains:
            f.write(f"+.{d}\n")

    # 4. 生成 .srs (格式: DOMAIN-SUFFIX,domain)
    with open(os.path.join(ROOT_DIR, "us_stock_backbone.srs"), "w", encoding="utf-8") as f:
        for d in sorted_domains:
            f.write(f"DOMAIN-SUFFIX,{d}\n")

    # 5. 更新 README
    with open(os.path.join(PROJECT_DIR, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# US Stock Backbone Rules\n\nUpdated: {update_time}\n\n### Statistics\n\n| Region | Domains | Total |\n| :--- | :--- | :--- |\n| US | {total_count} | {total_count} |\n\n### Files\n\n- [us_stock_backbone.list](us_stock_backbone.list)\n- [us_stock_backbone.yaml](us_stock_backbone.yaml)\n- [us_stock_backbone.srs](us_stock_backbone.srs)\n\n### Auto Update\n\nThis file is automatically generated by GitHub Actions.")

    print(f"[+] 编译完成: 共处理 {total_count} 个核心域名。")

if __name__ == "__main__":
    main()
