import os
from datetime import datetime

# ============================================================
# 当前脚本所在目录：wenhua/scripts
# ============================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ============================================================
# wenhua 目录：wenhua/
# ============================================================
WENHUA_DIR = os.path.dirname(SCRIPT_DIR)

# ============================================================
# 仓库根目录：my-rules/
# ============================================================
ROOT_DIR = os.path.dirname(WENHUA_DIR)

# ============================================================
# 数据目录：wenhua/data/
# ============================================================
DATA_DIR = os.path.join(WENHUA_DIR, "data")

# ============================================================
# 文华财经只有 CN 区域
# ============================================================
REGIONS = ["cn"]


# ============================================================
# 读取 source.txt
# ============================================================
def load_domains(region):
    """读取 wenhua/data/{region}-source.txt"""
    path = os.path.join(DATA_DIR, f"{region}-source.txt")
    if not os.path.exists(path):
        return []

    domains = []
    with open(path, "r") as f:
        for line in f:
            d = line.strip()
            if d:
                domains.append(d)
    return domains


# ============================================================
# 生成 .list（根目录）
# ============================================================
def write_list(region, domains):
    """生成 wenhua_cn.list（Clash / Surge 通用）"""
    out = os.path.join(ROOT_DIR, f"wenhua_{region}.list")
    with open(out, "w") as f:
        for d in domains:
            if d.startswith("KEYWORD:"):
                f.write(d.replace("KEYWORD:", "") + "\n")
            else:
                f.write("+." + d + "\n")


# ============================================================
# 生成 .yaml（根目录）
# YAML 格式必须是：
# payload:
#   - +.domain.com
# ============================================================
def write_yaml(region, domains):
    """生成 wenhua_cn.yaml（你指定的格式）"""
    out = os.path.join(ROOT_DIR, f"wenhua_{region}.yaml")
    with open(out, "w") as f:
        f.write("payload:\n")
        for d in domains:
            if d.startswith("KEYWORD:"):
                name = d.replace("KEYWORD:", "")
                f.write(f"  - +.{name}\n")
            else:
                f.write(f"  - +.{d}\n")


# ============================================================
# 生成 .srs（Surge 格式）
# ============================================================
def write_srs(region, domains):
    """生成 wenhua_cn.srs（Surge DOMAIN-SUFFIX 格式）"""
    out = os.path.join(ROOT_DIR, f"wenhua_{region}.srs")
    with open(out, "w") as f:
        for d in domains:
            if d.startswith("KEYWORD:"):
                f.write(f"DOMAIN-KEYWORD,{d.replace('KEYWORD:', '')}\n")
            else:
                f.write(f"DOMAIN-SUFFIX,{d}\n")


# ============================================================
# 生成 wenhua/README.md
# ============================================================
def write_readme(all_stats):
    """生成 wenhua/README.md（带统计表）"""

    now = datetime.now().strftime("%Y--%m--%d")
    badge = f"https://img.shields.io/badge/Updated-{now}-success"

    table = (
        "| Region | Domains | Keywords | Total |\n"
        "|--------|---------|----------|-------|\n"
    )

    for region, stat in all_stats.items():
        table += (
            f"| {region.upper()} | "
            f"{stat['domains']} | "
            f"{stat['keywords']} | "
            f"{stat['total']} |\n"
        )

    file_list = ""
    for region in REGIONS:
        file_list += f"- `wenhua_{region}.list`\n"
        file_list += f"- `wenhua_{region}.yaml`\n"
        file_list += f"- `wenhua_{region}.srs`\n"

    readme_path = os.path.join(WENHUA_DIR, "README.md")
    with open(readme_path, "w") as f:
        f.write("# WenHua Rules\n\n")
        f.write(f"![Updated]({badge})\n\n")
        f.write("## Statistics\n")
        f.write(table + "\n")
        f.write("## Files\n")
        f.write(file_list + "\n")
        f.write("## Auto Update\n")
        f.write("This file is automatically generated by GitHub Actions.\n")


# ============================================================
# 主流程
# ============================================================
def main():
    all_stats = {}

    for region in REGIONS:
        domains = load_domains(region)

        count_domain = sum(1 for d in domains if not d.startswith("KEYWORD:"))
        count_keyword = sum(1 for d in domains if d.startswith("KEYWORD:"))
        total = len(domains)

        all_stats[region] = {
            "domains": count_domain,
            "keywords": count_keyword,
            "total": total,
        }

        write_list(region, domains)
        write_yaml(region, domains)
        write_srs(region, domains)

    write_readme(all_stats)

    print("Generate complete.")


# ============================================================
# 入口
# ============================================================
if __name__ == "__main__":
    main()
