import os
from datetime import datetime

# 当前脚本所在目录：huatai/scripts
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# huatai 目录：huatai/
HUATAI_DIR = os.path.dirname(SCRIPT_DIR)

# 仓库根目录：my-rules/
ROOT_DIR = os.path.dirname(HUATAI_DIR)

# 数据目录：huatai/data/
DATA_DIR = os.path.join(HUATAI_DIR, "data")

REGIONS = ["cn", "hk", "us", "sg"]


# -----------------------------
# 读取 source.txt
# -----------------------------
def load_domains(region):
    path = os.path.join(DATA_DIR, f"{region}-source.txt")
    if not os.path.exists(path):
        return []

    domains = []
    with open(path, "r") as f:
        for line in f:
            d = line.strip()
            if d:
                domains.append(d)
    return domains


# -----------------------------
# 生成 .list（根目录）
# -----------------------------
def write_list(region, domains):
    out = os.path.join(ROOT_DIR, f"huatai_{region}.list")
    with open(out, "w") as f:
        for d in domains:
            if d.startswith("KEYWORD:"):
                f.write(d.replace("KEYWORD:", "") + "\n")
            else:
                f.write("+." + d + "\n")


# -----------------------------
# 生成 .yaml（根目录）
# -----------------------------
def write_yaml(region, domains):
    out = os.path.join(ROOT_DIR, f"huatai_{region}.yaml")
    with open(out, "w") as f:
        f.write("payload:\n")
        for d in domains:
            if d.startswith("KEYWORD:"):
                f.write(f"  - DOMAIN-KEYWORD,{d.replace('KEYWORD:', '')}\n")
            else:
                f.write(f"  - DOMAIN-SUFFIX,{d}\n")


# -----------------------------
# 生成 .srs（根目录，Surge）
# -----------------------------
def write_srs(region, domains):
    out = os.path.join(ROOT_DIR, f"huatai_{region}.srs")
    with open(out, "w") as f:
        for d in domains:
            if d.startswith("KEYWORD:"):
                f.write(f"DOMAIN-KEYWORD,{d.replace('KEYWORD:', '')}\n")
            else:
                f.write(f"DOMAIN-SUFFIX,{d}\n")


# -----------------------------
# 生成 huatai/README.md（豪华版）
# -----------------------------
def write_readme(all_stats):
    # 更新时间徽章
    now = datetime.now().strftime("%Y--%m--%d")
    badge = f"https://img.shields.io/badge/Updated-{now}-success"

    # 统计表格
    table = (
        "| Region | Domains | Keywords | Total |\n"
        "|--------|---------|----------|-------|\n"
    )
    for region, stat in all_stats.items():
        table += (
            f"| {region.upper()} | "
            f"{stat['domains']} | "
            f"{stat['keywords']} | "
            f"{stat['total']} |\n"
        )

    # 文件说明
    file_list = ""
    for region in REGIONS:
        file_list += f"- `huatai_{region}.list`\n"
        file_list += f"- `huatai_{region}.yaml`\n"
        file_list += f"- `huatai_{region}.srs`\n"

    # 写入 huatai/README.md（注意这里用的是 HUATAI_DIR）
    readme_path = os.path.join(HUATAI_DIR, "README.md")
    with open(readme_path, "w") as f:
        f.write("# Huatai Rules\n\n")
        f.write(f"![Updated]({badge})\n\n")
        f.write("## Statistics\n")
        f.write(table + "\n")
        f.write("## Files\n")
        f.write(file_list + "\n")
        f.write("## Auto Update\n")
        f.write("This file is automatically generated by GitHub Actions.\n")


# -----------------------------
# 主流程
# -----------------------------
def main():
    all_stats = {}

    for region in REGIONS:
        domains = load_domains(region)

        count_domain = sum(1 for d in domains if not d.startswith("KEYWORD:"))
        count_keyword = sum(1 for d in domains if d.startswith("KEYWORD:"))
        total = len(domains)

        all_stats[region] = {
            "domains": count_domain,
            "keywords": count_keyword,
            "total": total,
        }

        write_list(region, domains)
        write_yaml(region, domains)
        write_srs(region, domains)

    write_readme(all_stats)

    print("Generate complete.")


if __name__ == "__main__":
    main()

